<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.01" os="Windows 7" host="HW1419"><DocLocation><![CDATA[C:\IFSAutomation\Branch_IFS_Documents_Final\Drivers\SuiteDriver]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[SuiteDriver]]></DName>
<Res><![CDATA[Res238]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[07-09-2016 - 13:36:31]]></Time>
<TimeTick>1473235591</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",3]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",3]]></Details>
<Time><![CDATA[07-09-2016 - 13:36:31]]></Time>
<TimeTick>1473235591</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="10" status="Passed" >
<Disp><![CDATA[Run "iexplore.exe",3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="9" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[07-09-2016 - 13:36:33]]></Time>
<TimeTick>1473235593</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "Login" (of class Browser). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[07-09-2016 - 13:36:33]]></Time>
<TimeTick>1473235593</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>miccommentproperty = <br>Mercury Class = Browser<br>CreationTime = 0<br>|Title = Login - Windows Internet Explorer<br>openurl = http://www.msn.com/en-in/?cobrand=dell13.msn.com&ocid=DELLDHP&pc=MDDCJS<br>opentitle = <br>Opened By Testing Tool = 0<br>number of tabs = 1<br>Name = Login<br>]]></Details>
<Time><![CDATA[07-09-2016 - 13:36:33]]></Time>
<TimeTick>1473235593</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="22" status="Warning" nType="Description" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="21" status="Failed" nType="Run Error" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="20" status="Failed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Login&quot; (of class Browser). Verify that this object's properties match an object currently displayed in your application.<BR>Function file: C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs<BR>Line (10): &quot;		Browser(&quot;Login&quot;).Page(&quot;Login&quot;).sync&quot;.]]></Details>
<Time><![CDATA[07-09-2016 - 13:36:33]]></Time>
<TimeTick>1473235593</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="23" status="Failed" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="9" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[LoginInvalidUser]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[07-09-2016 - 13:36:33]]></Time>
<TimeTick>1473235593</TimeTick>
<NodeArgs eType="User" icon="7" nRep="24" status="Passed" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[LoginInvalidUser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:01]]></Time>
<TimeTick>1473235621</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:01]]></Time>
<TimeTick>1473235621</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[TXT_user_name.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:01]]></Time>
<TimeTick>1473235621</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="28" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[TXT_user_name.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[TXT_user_name.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["user"]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:01]]></Time>
<TimeTick>1473235621</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="30" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[TXT_user_name.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="27" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="26" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA[LoginInvalidUser]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:01]]></Time>
<TimeTick>1473235621</TimeTick>
<NodeArgs eType="User" icon="7" nRep="31" status="Passed" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[LoginInvalidUser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:01]]></Time>
<TimeTick>1473235621</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:01]]></Time>
<TimeTick>1473235621</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[TXT_user_password.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:01]]></Time>
<TimeTick>1473235621</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="35" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[TXT_user_password.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[TXT_user_password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["user"]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:01]]></Time>
<TimeTick>1473235621</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="37" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[TXT_user_password.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="34" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="33" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj ><![CDATA[LoginInvalidUser]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:01]]></Time>
<TimeTick>1473235621</TimeTick>
<NodeArgs eType="User" icon="7" nRep="38" status="Passed" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[LoginInvalidUser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:01]]></Time>
<TimeTick>1473235621</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:01]]></Time>
<TimeTick>1473235621</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[BTN_Log In.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:01]]></Time>
<TimeTick>1473235621</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="42" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[BTN_Log In.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[BTN_Log In.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:04]]></Time>
<TimeTick>1473235624</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="44" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[BTN_Log In.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="41" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="40" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[LoginInvalidUser]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:04]]></Time>
<TimeTick>1473235624</TimeTick>
<NodeArgs eType="User" icon="7" nRep="45" status="Passed" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[LoginInvalidUser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:07]]></Time>
<TimeTick>1473235627</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:07]]></Time>
<TimeTick>1473235627</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[TXT_user_password.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:07]]></Time>
<TimeTick>1473235627</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="49" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[TXT_user_password.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[TXT_user_password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["chrisj"]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:07]]></Time>
<TimeTick>1473235627</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="51" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[TXT_user_password.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="48" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="47" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj ><![CDATA[LoginInvalidUser]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:07]]></Time>
<TimeTick>1473235627</TimeTick>
<NodeArgs eType="User" icon="7" nRep="52" status="Passed" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[LoginInvalidUser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:07]]></Time>
<TimeTick>1473235627</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:07]]></Time>
<TimeTick>1473235627</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[BTN_Log In.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:07]]></Time>
<TimeTick>1473235627</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="56" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[BTN_Log In.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[BTN_Log In.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:10]]></Time>
<TimeTick>1473235630</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="58" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[BTN_Log In.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="55" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="54" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA[LoginInvalidUser]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[07-09-2016 - 13:37:10]]></Time>
<TimeTick>1473235630</TimeTick>
<NodeArgs eType="User" icon="7" nRep="59" status="Passed" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[LoginInvalidUser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[07-09-2016 - 13:38:10]]></Time>
<TimeTick>1473235690</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[07-09-2016 - 13:38:10]]></Time>
<TimeTick>1473235690</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[TXT_user_password.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[07-09-2016 - 13:38:10]]></Time>
<TimeTick>1473235690</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="64" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[TXT_user_password.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="63" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="62" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA[LoginInvalidUser]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[07-09-2016 - 13:38:10]]></Time>
<TimeTick>1473235690</TimeTick>
<NodeArgs eType="User" icon="7" nRep="65" status="Failed" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[LoginInvalidUser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[07-09-2016 - 13:39:11]]></Time>
<TimeTick>1473235751</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[07-09-2016 - 13:39:11]]></Time>
<TimeTick>1473235751</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[BTN_Log In.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[07-09-2016 - 13:39:11]]></Time>
<TimeTick>1473235751</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="70" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[BTN_Log In.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="69" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="68" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj ><![CDATA[LoginInvalidUser]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[07-09-2016 - 13:39:11]]></Time>
<TimeTick>1473235751</TimeTick>
<NodeArgs eType="User" icon="7" nRep="71" status="Failed" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[LoginInvalidUser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[07-09-2016 - 13:40:11]]></Time>
<TimeTick>1473235811</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[07-09-2016 - 13:40:11]]></Time>
<TimeTick>1473235811</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[TXT_user_password.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[07-09-2016 - 13:40:11]]></Time>
<TimeTick>1473235811</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="76" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[TXT_user_password.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="75" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="74" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[LoginInvalidUser]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[07-09-2016 - 13:40:11]]></Time>
<TimeTick>1473235811</TimeTick>
<NodeArgs eType="User" icon="7" nRep="77" status="Failed" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[LoginInvalidUser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[07-09-2016 - 13:41:12]]></Time>
<TimeTick>1473235872</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[07-09-2016 - 13:41:12]]></Time>
<TimeTick>1473235872</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[BTN_Log In.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[07-09-2016 - 13:41:12]]></Time>
<TimeTick>1473235872</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="82" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[BTN_Log In.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="81" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="80" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[LoginInvalidUser]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[07-09-2016 - 13:41:12]]></Time>
<TimeTick>1473235872</TimeTick>
<NodeArgs eType="User" icon="7" nRep="83" status="Failed" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[LoginInvalidUser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[07-09-2016 - 13:42:12]]></Time>
<TimeTick>1473235932</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[07-09-2016 - 13:42:12]]></Time>
<TimeTick>1473235932</TimeTick>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[TXT_user_password.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[07-09-2016 - 13:42:12]]></Time>
<TimeTick>1473235932</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="88" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[TXT_user_password.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="87" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="86" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj ><![CDATA[LoginInvalidUser]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[07-09-2016 - 13:42:12]]></Time>
<TimeTick>1473235932</TimeTick>
<NodeArgs eType="User" icon="7" nRep="89" status="Failed" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[LoginInvalidUser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[07-09-2016 - 13:43:13]]></Time>
<TimeTick>1473235993</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[07-09-2016 - 13:43:13]]></Time>
<TimeTick>1473235993</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[BTN_Log In.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[07-09-2016 - 13:43:13]]></Time>
<TimeTick>1473235993</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="101" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[BTN_Log In.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="100" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="99" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA[LoginInvalidUser]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[07-09-2016 - 13:43:13]]></Time>
<TimeTick>1473235993</TimeTick>
<NodeArgs eType="User" icon="7" nRep="102" status="Failed" Source="C:\IFSAutomation\Branch_IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[LoginInvalidUser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[07-09-2016 - 13:44:14]]></Time>
<TimeTick>1473236054</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>