<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.01" os="Windows 7" host="HW2314"><DocLocation><![CDATA[C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Drivers\SuiteDriver]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[SuiteDriver]]></DName>
<Res><![CDATA[Res147]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:01]]></Time>
<TimeTick>1454578801</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",3]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",3]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:01]]></Time>
<TimeTick>1454578801</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="10" status="Passed" >
<Disp><![CDATA[Run "iexplore.exe",3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="9" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:02]]></Time>
<TimeTick>1454578802</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "Login" (of class Browser). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:02]]></Time>
<TimeTick>1454578802</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>miccommentproperty = <br>Mercury Class = Browser<br>CreationTime = 0<br>|Title = Login - Windows Internet Explorer<br>openurl = http://www.msn.com/en-in/?cobrand=dell13.msn.com&ocid=DELLDHP&pc=MDDCJS<br>opentitle = <br>Opened By Testing Tool = 0<br>number of tabs = 1<br>Name = Login<br>]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:02]]></Time>
<TimeTick>1454578802</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="22" status="Warning" nType="Description" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="21" status="Failed" nType="Run Error" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="20" status="Failed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Login&quot; (of class Browser). Verify that this object's properties match an object currently displayed in your application.<BR>Function file: C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs<BR>Line (10): &quot;		Browser(&quot;Login&quot;).Page(&quot;Login&quot;).sync&quot;.]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:02]]></Time>
<TimeTick>1454578802</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="23" status="Failed" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="9" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:02]]></Time>
<TimeTick>1454578802</TimeTick>
<NodeArgs eType="User" icon="7" nRep="24" status="Passed" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:08]]></Time>
<TimeTick>1454578808</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:08]]></Time>
<TimeTick>1454578808</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[TXT_user_name.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:08]]></Time>
<TimeTick>1454578808</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="58" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[TXT_user_name.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[TXT_user_name.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["chrisj"]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:08]]></Time>
<TimeTick>1454578808</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="60" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[TXT_user_name.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="57" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="56" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:08]]></Time>
<TimeTick>1454578808</TimeTick>
<NodeArgs eType="User" icon="7" nRep="61" status="Passed" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:08]]></Time>
<TimeTick>1454578808</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:08]]></Time>
<TimeTick>1454578808</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[TXT_user_password.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:08]]></Time>
<TimeTick>1454578808</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="65" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[TXT_user_password.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[TXT_user_password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["password"]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:08]]></Time>
<TimeTick>1454578808</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="67" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[TXT_user_password.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="64" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="63" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:08]]></Time>
<TimeTick>1454578808</TimeTick>
<NodeArgs eType="User" icon="7" nRep="68" status="Passed" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:08]]></Time>
<TimeTick>1454578808</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:08]]></Time>
<TimeTick>1454578808</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[BTN_Log In.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:08]]></Time>
<TimeTick>1454578808</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="72" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[BTN_Log In.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[BTN_Log In.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:11]]></Time>
<TimeTick>1454578811</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="74" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[BTN_Log In.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="71" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="70" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:11]]></Time>
<TimeTick>1454578811</TimeTick>
<NodeArgs eType="User" icon="7" nRep="75" status="Passed" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:14]]></Time>
<TimeTick>1454578814</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:14]]></Time>
<TimeTick>1454578814</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[TAB _Home.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:14]]></Time>
<TimeTick>1454578814</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="79" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[TAB _Home.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Work Queue.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:14]]></Time>
<TimeTick>1454578814</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="81" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Work Queue.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[TAB _Home.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:19]]></Time>
<TimeTick>1454578819</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="83" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[TAB _Home.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="78" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="77" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:19]]></Time>
<TimeTick>1454578819</TimeTick>
<NodeArgs eType="User" icon="7" nRep="84" status="Passed" Source="C:\IFSAutomation\IFS_Documents_Final\IFS_Documents_Final\Libraries\GeneralLibraries\BusinessFunction.vbs" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:23]]></Time>
<TimeTick>1454578823</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:23]]></Time>
<TimeTick>1454578823</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[TAB _Home.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:23]]></Time>
<TimeTick>1454578823</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="88" >
<Disp><![CDATA[TAB _Home.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="87" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="86" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA[NavigateToDraftMode]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:23]]></Time>
<TimeTick>1454578823</TimeTick>
<NodeArgs eType="User" icon="7" nRep="89" status="Passed" >
<Disp><![CDATA[NavigateToDraftMode]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:26]]></Time>
<TimeTick>1454578826</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:26]]></Time>
<TimeTick>1454578826</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[TAB_Tests.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:26]]></Time>
<TimeTick>1454578826</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="93" >
<Disp><![CDATA[TAB_Tests.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="92" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="91" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA[NavigateToDraftMode]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:26]]></Time>
<TimeTick>1454578826</TimeTick>
<NodeArgs eType="User" icon="7" nRep="94" status="Passed" >
<Disp><![CDATA[NavigateToDraftMode]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:29]]></Time>
<TimeTick>1454578829</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:29]]></Time>
<TimeTick>1454578829</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[TAB_Tests.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:29]]></Time>
<TimeTick>1454578829</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="98" >
<Disp><![CDATA[TAB_Tests.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[TAB_Tests.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:32]]></Time>
<TimeTick>1454578832</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="100" >
<Disp><![CDATA[TAB_Tests.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="97" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="96" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[NavigateToDraftMode]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:32]]></Time>
<TimeTick>1454578832</TimeTick>
<NodeArgs eType="User" icon="7" nRep="101" status="Passed" >
<Disp><![CDATA[NavigateToDraftMode]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:35]]></Time>
<TimeTick>1454578835</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:35]]></Time>
<TimeTick>1454578835</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[LNK_Draft Mode.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:35]]></Time>
<TimeTick>1454578835</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="105" >
<Disp><![CDATA[LNK_Draft Mode.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="104" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="103" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA[NavigateToDraftMode]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:35]]></Time>
<TimeTick>1454578835</TimeTick>
<NodeArgs eType="User" icon="7" nRep="106" status="Passed" >
<Disp><![CDATA[NavigateToDraftMode]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:38]]></Time>
<TimeTick>1454578838</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:38]]></Time>
<TimeTick>1454578838</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[LNK_Draft Mode.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:38]]></Time>
<TimeTick>1454578838</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="110" >
<Disp><![CDATA[LNK_Draft Mode.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[LNK_Draft Mode.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:41]]></Time>
<TimeTick>1454578841</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="112" >
<Disp><![CDATA[LNK_Draft Mode.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="109" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="108" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA[NavigateToDraftMode]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:41]]></Time>
<TimeTick>1454578841</TimeTick>
<NodeArgs eType="User" icon="7" nRep="113" status="Passed" >
<Disp><![CDATA[NavigateToDraftMode]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Entry]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:49]]></Time>
<TimeTick>1454578849</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Entry]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:49]]></Time>
<TimeTick>1454578849</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[LBL_Header_DraftModeEntry.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:49]]></Time>
<TimeTick>1454578849</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="117" >
<Disp><![CDATA[LBL_Header_DraftModeEntry.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="116" >
<Disp><![CDATA[Entry]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="115" >
<Disp><![CDATA[Entry]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj ><![CDATA[VerifyWarningMessageRemoved]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:49]]></Time>
<TimeTick>1454578849</TimeTick>
<NodeArgs eType="User" icon="7" nRep="118" status="Passed" >
<Disp><![CDATA[VerifyWarningMessageRemoved]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Entry]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:52]]></Time>
<TimeTick>1454578852</TimeTick>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Entry]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:52]]></Time>
<TimeTick>1454578852</TimeTick>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[LBL_Header_DraftModeEntry.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:52]]></Time>
<TimeTick>1454578852</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="122" >
<Disp><![CDATA[LBL_Header_DraftModeEntry.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="121" >
<Disp><![CDATA[Entry]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="120" >
<Disp><![CDATA[Entry]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj ><![CDATA[VerifyWarningMessageRemoved]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:52]]></Time>
<TimeTick>1454578852</TimeTick>
<NodeArgs eType="User" icon="7" nRep="123" status="Passed" >
<Disp><![CDATA[VerifyWarningMessageRemoved]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Entry]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:55]]></Time>
<TimeTick>1454578855</TimeTick>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Entry]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:55]]></Time>
<TimeTick>1454578855</TimeTick>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[LBL_PageMessage_Thispagecontainrequired.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:55]]></Time>
<TimeTick>1454578855</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="127" >
<Disp><![CDATA[LBL_PageMessage_Thispagecontainrequired.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="126" >
<Disp><![CDATA[Entry]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="125" >
<Disp><![CDATA[Entry]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj ><![CDATA[VerifyWarningMessageRemoved]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:55]]></Time>
<TimeTick>1454578855</TimeTick>
<NodeArgs eType="User" icon="7" nRep="128" status="Passed" >
<Disp><![CDATA[VerifyWarningMessageRemoved]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Entry]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:58]]></Time>
<TimeTick>1454578858</TimeTick>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Entry]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:58]]></Time>
<TimeTick>1454578858</TimeTick>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[LBL_Warning_Answer theDropDownquestion.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:58]]></Time>
<TimeTick>1454578858</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="132" >
<Disp><![CDATA[LBL_Warning_Answer theDropDownquestion.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="131" >
<Disp><![CDATA[Entry]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="130" >
<Disp><![CDATA[Entry]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj ><![CDATA[VerifyWarningMessageRemoved]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[04-02-2016 - 15:10:58]]></Time>
<TimeTick>1454578858</TimeTick>
<NodeArgs eType="User" icon="7" nRep="133" status="Passed" >
<Disp><![CDATA[VerifyWarningMessageRemoved]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">